### ISSUE TITLE
根据大小缩放，自动截取文字 text-overflow: ellipsis; / tailwindcss: truncate

### ISSUE THREAD

**Issue by davidkorea** [davidkorea/30days_frontend#2]
- 截取文字长度
    ```css
    .desc {
        height: 20%;
        color: gray;
        font-weight: 200;
        font-size: 12px;
        
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
    ```
    <img width="574" src="https://user-images.githubusercontent.com/26485327/75113770-74e79b80-568b-11ea-9439-7e16c120dd9b.png">

    - 设置好height或者width
    - 在添加下面三个属性，text-overflow会根据div尺寸自动截取并在末尾添加三个点...
        - `overflow: hidden;`
        - `text-overflow: ellipsis;`
        - `white-space: nowrap;`
